variables:
  SQUARE_OBSERVABILITY: "true"

default:
  interruptible: true
  tags:
    - square_windows

build_and_publish:
  stage: build
  script:
    - .\build\TeaBox.com Build
    - .\build\TeaBox.com PublishNugetPackage -ProjectPath:UbiDirStat/UbiDirStat.csproj

publish_installer:
  stage: deploy
  needs: [ "build_and_publish"]
  script:
    - .\build\TeaBox.com GenerateFacadeInstaller -ExeFilterRegex:UbiDirStat\.exe$ -RunMode:SeparateProcess -PackageName:UbiDirStat -PackageVersion:latest -OutputFolder:GeneratedInstaller -Housekeep:true -DisplayUpdateWindow:true
    - .\build\TeaBox.com PublishGenericFile -FilePath:GeneratedInstaller\UbiDirStatInstaller.exe
  only:
    - tags
